[metadata]
name = phaderkampit
version = 0.1.0
description = Audio quiz app foundation
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
install_requires =
    flask>=3.0.0
    flask-sqlalchemy>=3.1.1
    psycopg2-binary>=2.9.9
    python-dotenv>=1.0.1
    gunicorn>=21.2.0
python_requires = >=3.10
